rem this file is for code generation purposes only
rem it cannot run on any basic interpreter
1?CHR$(147):SCREEN$03:?CHR$($90)CHR$(1)CHR$(147)CHR$($9E);
2H$="**** PASSPHRASE GENERATOR ****"
3S=INT(20-LEN(H$)/2):?SPC(S)H$SPC(S):?"":H$="AUTHOR: WU TINGFENG"
4S=INT(20-LEN(H$)/2):?SPC(S)H$SPC(S):?"":?"":H$="LICENSE: BSD-3-CLAUSE"
5S=INT(20-LEN(H$)/2):?SPC(S)H$SPC(S):?""
6NUMROLLS=4:LOWOUTCOME=INT((6^NUMROLLS-1)/(6-1))-1
7DIMD(NUMROLLS):FORI=1TONUMROLLS:D(I)=6^(NUMROLLS-I):NEXT
8?CHR$($99):W$="":INPUT"ENTER NUMBER OF WORDS TO GENERATE (3-20)";W$
9PASSPHRASESIZE=VAL(W$):IFPASSPHRASESIZE<3ORPASSPHRASESIZE>20THEN8
10R=RND(-TI):?CHR$($05):FORK=1TOPASSPHRASESIZE:N=-LOWOUTCOME
11FORI=1TONUMROLLS:N=N+((INT(RND(1)*6)+1)*INT(D(I))):NEXT
12?O$(N):NEXT
13?CHR$($9A):A$="":INPUT"GENERATE ANOTHER PASSPHRASE (Y/N)";A$
14IFA$<>"Y"ANDA$<>"N"THEN13
15IFA$="N"THEN17
16GOTO8
17?CHR$($99);:END
